# Generated by Django 4.1.4 on 2022-12-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_whatido_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivered',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_experience',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
